config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get '/page/:page', action: :index, on: :collection
  end
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_one_attached :image
  paginates_per 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:role)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.page params[:page]
  end

  # GET /users/1 or /users/1.json
  def show
  end

  def new
    @roles = Role.all
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :image, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotvue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Role:</strong>
    <%= role.role %>
  </p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>

app/views/users/_form.html.erb
<div style="width: 300px; padding: 10px">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div  class="field form-group">
      <% form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
    </div>
    <br>

    <div  class="field form-group">
      <% form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
    </div>
    <br>

    <div  class="field form-group">
      <% form.label :image %>
      <%= form.file_field :image, class:"form-control", placeholder:"Last Name"  %>
    </div>
    <br>

    <div  class="field form-group">
      <%= form.label :role_id, style: "display: block" %>
      <%= form.collection_select :role_id, Role.order(:role),:id,:role, include_blank: true, class: "dropdown-center" %>
    </div>

    <br>
      <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
      </div>
  <% end %>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to user.image.filename, user.image if user.image.attached? %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role.role %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="container " style="margin: 40px">
  <div>
    <h2>Welcome to Lotvue</h2>
  </div>
  <table class="table table-striped table-bordered table-hover"  style="margin: 40px; margin-left: 0px">
    <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Role</th>
      <th> </th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.first_name + ' ' + user.last_name, user %>
        </td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.role.role %></td>
        <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>

    <%= link_to 'New User', new_user_path, class:"btn btn-secondary" %>


</div>

<div  style="margin: 50px">
  <%= paginate @users %>
  <br>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to 'Back to users', users_path, class:"btn btn-dark" %>

</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h3 class="display-7">
    <%= @user.first_name %>
    <%= @user.last_name %>
  </h3>
  <p class="lead">
    <%= @user.role.role %>

  <div style="width: 150px; height: 150px">
    <%= image_tag@user.image, style: 'width: 150px' %>
  </div>

  </p>
  <br/>

  <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-secondary" %>


  <%= link_to 'Back', users_path, class:"btn btn-dark" %>

  <%= button_to 'Delete', @user, method: :delete, class: "btn btn-danger" %>

</div>